### PR TITLE
Switch png rendering to cairo. Removes Xserver requirement.

### PR DESCRIPTION
**Pull request by andynu**

### CODE REVIEW

**Comment by alexlancaster** [comment]
Great, Andy!  Excellent that we no longer need the X requirement.

**Comment by andynu** [comment]
All thanks to @moskrin for figuring out and implementing it.

**Comment by alexlancaster** [comment]
Nice, thanks.  I went to go and "Like" your comment @andynu then I realised that this is github!

**Comment by andynu** [comment]
:+1:  hahaha. https://github.com/dear-github/dear-github

**Pull request merged**
