### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by AstrobioMike**
minor type in explanation :)

### CODE REVIEW

**Comment by AstrobioMike** [comment]
actually now i'm confusing myself. I apologize if i'm mis-reading this and maybe this suggestion is completely wrong, ha

**Comment by alexlancaster** [comment]
Thanks for being interested!  Hope you've found the tool useful!

**Comment by AstrobioMike** [comment]
Absolutely, guiding some very cool work my colleagues are doing in the lab :) Thanks!

**Comment by oliverking** [comment]
Thanks --- I think this is okay as it was: PLAAC always uses the foreground
(prion-like) AA freqs from yeast, so when one uses the pure background AA
freqs from species X (a=0) one is essentially assuming that the prion-like
AA freqs are the same in species X as in yeast, i.e. that they are
species-independent, when computing likelihood ratios. Using a>0 softens
this assumption, not by trying to adjust the prion-like AA freqs for
species X directly but rather by nudging the background AA frequencies for
species X towards those of yeast, which will nudge the likelihood ratios
for species X toward those in yeast.

**Comment by AstrobioMike** [comment]
Yeah I agree, now that I have my head oriented properly, just took me a while to get there, haha. Thanks again!

**Pull request closed without merging**
